name: Run Ingame Tests
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [push]
jobs:
  Run-Ingame-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: wget -q -O godot.zip https://github.com/godotengine/godot-builds/releases/download/4.4-beta1/Godot_v4.4-beta1_linux.x86_64.zip
      - run: unzip godot.zip
      - run: ./Godot_v4.4-beta1_linux.x86_64 -v --headless -e --quit
      - run: ./Godot_v4.4-beta1_linux.x86_64 -v --headless -e --quit # <-- double to ensure that we have everything in place from imports
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/game_starts.tscn --headless
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/player_jumps.tscn --headless
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/can_collect_coins.tscn --headless
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/pause_on_off.tscn --headless
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/stochastic_inputs.tscn --headless
