name: Run Ingame Tests
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [push]
jobs:
  Run-Ingame-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download Godot Engine
      - run: wget -q -O godot.zip https://github.com/godotengine/godot-builds/releases/download/4.4-beta1/Godot_v4.4-beta1_linux.x86_64.zip
      - name: Unzip Godot Engine
      - run: unzip godot.zip
      - name: Test if the game starts
      - run: ./Godot_v4.4-beta1_linux.x86_64 ./tests/game_starts.tscn --headless
